FROM php:8.2-fpm

# Install dependencies yang dibutuhkan
RUN apt-get update && apt-get install -y \
    libicu-dev \
    g++ \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    zip \
    unzip \
    git \
 && docker-php-ext-configure gd --with-freetype --with-jpeg \
 && docker-php-ext-install -j$(nproc) \
    gd \
    mysqli \
    pdo \
    pdo_mysql \
    intl \
    exif \
    zip \
    bcmath \
    opcache \
 && rm -rf /var/lib/apt/lists/*

# Pastikan ekstensi intl di-load
RUN echo "extension=intl" > /usr/local/etc/php/conf.d/docker-php-ext-intl.ini

WORKDIR /var/www/html

# (Opsional) Aktifkan opcache config
#COPY ./opcache.ini /usr/local/etc/php/conf.d/opcache.ini

# (Opsional) Tambahkan Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

